image: python:3.8-buster
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - pip install mkdocs
  - pip install mkdocstrings
  - pip install mkdocs-material
  - pip install dhtk/.
  - pip install dhtk-extension-gutenberg/.
pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main