site_name: The Digital Humanities ToolKit

nav:
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Guides:
    - User Guide: user_guide.md
    - Developer Guide: dev_guide.md
  - About: about.md
  - FAQ: faq.md
  - API:
    - API/DHTK.md

theme:
  #name: gitbook
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  # make code copyable to clipboard and annotatable
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - footnotes
  # For admonitions (info/notes/warnings/etc. extendable blocks)
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # For code blocks and highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Use markdown in HTML blocks
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: yes